### ISSUE TITLE
Add Velocity support

### ISSUE THREAD

**Issue by OpenSourceSlime** [sparkedhost/PteroBungee#3]

**Comment by BetTD** [comment]
Wasn’t there a compatibility layer for Velocity of some sorts that allowed BungeeCord plugins to function? I’ll still look into a native Velocity version, but I wanted to recode this plugin  regardless as it was made quite some time ago.

**Comment by OpenSourceSlime** [comment]
https://forums.velocitypowered.com/t/snap-run-bungeecord-plugins-on-velocity/608

I would still prefer a native port rather than this.

**Comment by BetTD** [comment]
I'll see what I can do

**Comment by BetTD** [comment]
@kerostampcrab So turns out Velocity is a big departure from what I'm used to, but I managed to get it to work because of its simplicity. Could you please test this on a real Velocity deployment? I was only able to test the stop functionality from the console, but I need to know if the stop command actually gets forwarded to chat when executed by a player (i.e. to attempt to stop a backend server) instead of stopping the proxy entirely. I can't see why it wouldn't work, but I'm very new to this API, so I've probably missed something quite obvious.

Please let me know how it goes.

https://drive.google.com/file/d/1vg6dKOPU_H7nk_fSsotO6Sw1BPwNY0-O/view?usp=sharing

**Comment by OpenSourceSlime** [comment]
> @kerostampcrab Could you please test this on a real Velocity deployment? I was only able to test the stop functionality from the console, but I need to know if the stop command actually gets forwarded to chat when executed by a player (i.e. to attempt to stop a backend server) instead of stopping the proxy entirely.

I didn't really understand, what should I try?
It does seem to work fine tho.

**Comment by BetTD** [comment]
> > @kerostampcrab Could you please test this on a real Velocity deployment? I was only able to test the stop functionality from the console, but I need to know if the stop command actually gets forwarded to chat when executed by a player (i.e. to attempt to stop a backend server) instead of stopping the proxy entirely.
> 
> I didn't really understand, what should I try? It does seem to work fine tho.


Try running /stop ingame, it should stop the backend server you're connected to instead of the proxy. Please let me know if it works.

**Comment by OpenSourceSlime** [comment]
Yeah it seems to work just fine.

**Comment by BetTD** [comment]
Awesome

**Comment by BetTD** [comment]
New release will be published soon.
